version: 2.1

orbs:
  go: circleci/go@3.0.2

jobs:
  test:
    executor:
      name: go/default
      tag: '1.25'
    steps:
      - checkout
      - go/mod-download
      - go/test:
          covermode: atomic
          failfast: true
          race: true

workflows:
  check:
    jobs:
      - test